const router         = require('express').Router();
const ctrl           = require('../controllers/personaJuntaDirectiva.controller');
const { verifyToken } = require('../middlewares/auth.middleware');
router.use(verifyToken);
router.get('/',      ctrl.listar);
router.get('/:id',   ctrl.obtener);
router.post('/',     ctrl.crear);
router.put('/:id',   ctrl.actualizar);
router.delete('/:id', ctrl.eliminar);
module.exports = router;